### ISSUE TITLE
(mbedOS porting) Official sample freezes after a couple of minutes

### ISSUE THREAD

**Issue by maiorfi** [eclipse/paho.mqtt.embedded-c#106]
I posted issue detail here:

https://developer.mbed.org/questions/79000/MQTT-Hello-world-on-NUCLEO_F429ZI-and-F7/

**Comment by icraggs** [comment]
Hi.  My IBM Watson IoTP application using the same underlying client code on a K64F and LPC1768 keeps working indefinitely.  Is this device more constrained at all?  How much memory do you have available?

**Comment by icraggs** [comment]
The mbed MQTT library has now been updated, so I'm hoping this issue will be resolved or improved.  We'll deal with the consequences on the mbed site, so I'm closing this issue.  Thanks.
