### ISSUE TITLE
After call the func MQTTSerialize_connect, in the buf, it should be 4D 51 54 54("MQTT"), but i got 0D 51 54 54("MQTT").

### ISSUE THREAD

**Issue by ittopone** [eclipse/paho.mqtt.embedded-c#112]
After call the func MQTTSerialize_connect, in the buf, it should be 4D 51 54 54("MQTT"), but i got 0D 51 54 54("MQTT").

**Comment by scaprile** [comment]
Can you step the function with a debugger and see what happens ? Maybe another function is trashing your buffer with a beautiful "carriage return" ?

**Comment by icraggs** [comment]
This functionality has been working and used for a number of years.  In the absence of more information I'm going to close this issue.  If you do have more information you can reopen or create another issue.  Thanks.
