### ISSUE TITLE
What is the least value of timeout that can be set in MQTTYield function in MQTTClient example to reduce latency?

### ISSUE THREAD

**Issue by anchandan** [eclipse/paho.mqtt.embedded-c#119]

**Comment by CIPop** [comment]
To reduce the latency with which you are receiving data from the network, you should use a timeout value as large as possible.
That way, MQTTYield function will unblock immediately after a message is received. Of course, in a single-thread system this would also prevent your system from doing anything else.

**Comment by icraggs** [comment]
Answered.
