### ISSUE TITLE
create a socket fail, but NetworkConnect return 0

### ISSUE THREAD

**Issue by tjdai** [eclipse/paho.mqtt.embedded-c#123]
if (rc == 0)
{
	n->my_socket = socket(family, type, 0);
	if (n->my_socket != -1)
		rc = connect(n->my_socket, (struct sockaddr*)&address, sizeof(address));
}
return rc;

in the function NetworkConnect. if creating a  socket fails,value n->my_socket is -1, the function connect is not executed. so the function will return success directly.

**Comment by icraggs** [comment]
Thanks.  I've merged the PR.
