### ISSUE TITLE
getLenStringLen() not used in MQTTPacket.c

### ISSUE THREAD

**Issue by gkerrien38** [eclipse/paho.mqtt.embedded-c#125]
Hello

While compiling Paho with IAR EWARM C compiler (for STM32L475) there is a warning: 

MQTTPacket/src/MQTTPacket.c:191:5: warning: 'getLenStringLen' defined but not used [-Wunused-function]

It seems this function getLenStringLen() is not used.

Is it possible to use it , or remove it ?

It seems there is code in readMQTTLenString() that computes the string length but it does not call getLenStringLen(). It calls readInt() instead.

Bill

**Comment by CIPop** [comment]
👍 additional compiler verification should be enabled to catch issues such as this one.

**Comment by icraggs** [comment]
This was removed in commit 8b320ad01a06dced43ea6a7119f02cb79ca6054c
