### ISSUE TITLE
pubrel set to true?

### ISSUE THREAD

**Issue by abrownsword** [eclipse/paho.mqtt.embedded-c#140]
I am currently implementing a C++ client (based on my messaging layer of choice), using the low level C API and working through the synchronous Paho C++ embedded client code as it is easier to understand. Mostly done now, however I've run into a question in the reconnection code:

Where is the member variable 'pubrel' set to true? It appears to be used in several places and set to false in two places, but in the version I have (downloaded from GitHub just a couple of weeks ago) it doesn't appear to ever be set to true. Which means its not clear how a PUBREL ack on reconnection can ever be generated.

Can someone clarify what's going on with this in the code?

**Comment by icraggs** [comment]
In MQTT version 3.1.1 the DUP bit in the PUBREL packet is reserved and must be set to 0.  The DUP flag is only set on the PUBLISH packet.

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718022
