### ISSUE TITLE
C client does not connect to IP address in FreeRTOS

### ISSUE THREAD

**Issue by igough** [eclipse/paho.mqtt.embedded-c#147]
When using FreeRTOS, the C client does not connect to the broker if the address string passed to NetworkConnect is an IP address. This is because FreeRTOS_gethostbyname does not check if the address is already an IP address before firing it off for DNS lookup. If there is no DNS server defined, the lookup fails and NetworkConnect does not connect to the IP address.

Fix to follow in a pull request.

**Comment by icraggs** [comment]
Thank you for showing that fix.    I'll get it added myself if you don't submit a PR.

I don't know whether you know that FreeRTOS seems to have its own MQTT client library now?

**Comment by igough** [comment]
I have already submitted a PR, #148.

**Comment by igough** [comment]
I just looked around for the MQTT lib at FreeRTOS and did not see it. Do you have a link?

**Comment by icraggs** [comment]
Thanks for reopening the PR.  I found a reference to MQTT for FreeRTOS here: https://docs.aws.amazon.com/freertos/latest/userguide/freertos-lib-cloud-connectivity.html

Thanks for the fix - I will merge it.  It's not that I don't want you to use this (Paho) library, but the FreeRTOS support has never had the focus I'd like to have given it, as this is just one of various projects I've been working on.  Even if it had, this library is intended to be portable across operating systems, so unlikely to be as good as one coded specifically for an OS.
