### ISSUE TITLE
Having trouble with MQTT::CLIENT

### ISSUE THREAD

**Issue by gurujiSushrut** [eclipse/paho.mqtt.embedded-c#158]
error: 'MQTT' does not name a type

     MQTT::Client<IPStack, Countdown, AWS_IOT_MQTT_TX_BUF_LEN, AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS> client;

I have this Issue, please help

**Comment by icraggs** [comment]
You'll have to give some more information than that.  There are samples and build scripts in the repo which show how to compile.

Thoughts: 
- have you included the correct header file?
- is that the first error message - are there others?
- what OS are you using, what compiler?
