### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by ghost** [eclipse/paho.mqtt.embedded-c#162]
Hi,
I modify the example"paho.mqtt.embedded-c/MQTTClient-C/samples/linux/stdoutsubc" and do some testing. My test is to send 100 messages per second, but ten seconds later, I found the program abnormal exit， here the gdb log:
__________________________
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bd3bdf in isTopicMatched (topicFilter=0x4018a5 "/SH/S2M/0077b9ed25b69912736f", topicName=0x7fffffffd290)
    at /mnt/hgfs/Share/paho.mqtt.embedded-c-develop/MQTTClient-C/src/MQTTClient.c:160
160	        if (*curn == '/' && *curf != '/')
__________________________
Can you give me some advice on the above questions? Thank you!

**Comment by CIPop** [comment]
`topicName` seems to be corrupted in this case, causing the crash. Since you've modified the code, ensure that you are not corrupting the stack, etc.
Please provide the entire stack or gdb crash.
