### ISSUE TITLE
'class FP<void, void>' has no member named 'attach'

### ISSUE THREAD

**Issue by apanasara** [eclipse/paho.mqtt.embedded-c#167]
I am using FP.h  file in one of my arduino's sketch.

**my.h**
```
class myClass
{
  public:
        void myFunction(void);
        void setup();
  private:
        otherClass _oc;
}
```
**my.cpp**
```
void myClass::setup()
{
       _oc.fp1.attach(this,&myClass::myFunction);
}
```
**otherClass.h**
```
# include "FP.h"
class otherClass
{
   pubic:
         FP<void,void>fp1;
         FP<void,void>fp2;
         FP<void,void>fp3;
}
```
**_Error while Compilation_**

> ### 'class FP<void, void>' has no member named 'attach'

**Comment by icraggs** [comment]
This is a C++ question. You can't have a void value for the second parameter to the FP class constructor (as your compiler should tell you).
