### ISSUE TITLE
Error : declaration of 'MQTT::Client<WifiIPStack, Countdown, 100, 2> myClass::Countdown' [-fpermissive]

### ISSUE THREAD

**Issue by apanasara** [eclipse/paho.mqtt.embedded-c#168]
I have made myClass in which MQTT::Client is defined but I am getting following error during compilation

**_Error while compilation_**
> declaration of 'MQTT::Client<WifiIPStack, Countdown, 100, 2> myClass::Countdown' [-fpermissive]

**myClass.h**

```
#include <SPI.h>
#include <WifiIPStack.h>
#include <Countdown.h>
#include <MQTTClient.h>
class myClass
{
   private:
       WifiIPStack _ipstack;
       MQTT::Client<WifiIPStack,Countdown,100,2> _client = MQTT::Client<WifiIPStack, Countdown,100,2>(_ipstack);
}
```

**Comment by apanasara** [comment]
proper Initiation of Client class

**myClass.h**
```
#include <SPI.h>
#include <WifiIPStack.h>
#include <Countdown.h>
#include <MQTTClient.h>
class myClass
{
   private:
       WifiIPStack _ipstack;
       MQTT::Client<WifiIPStack,Countdown,100,2> _client(WifiIPStack);
}

```
**myClass.cpp**
```
_client(_ipstack);
```

**Comment by CIPop** [comment]
From what I see, the issues are caused by improper use of C++: did you mean to create a constructor for your class that properly initializes `_client`?

**Comment by icraggs** [comment]
Answered.
