### ISSUE TITLE
Question about this repository

### ISSUE THREAD

**Issue by sigusr1** [eclipse/paho.mqtt.embedded-c#196]
Is this repository discarded?

I found repository  [https://github.com/eclipse/paho.mqtt.c](https://github.com/eclipse/paho.mqtt.c) update frequently， but this repository hasn't updated for years.

**Comment by scaprile** [comment]
Embedded code can be mature without turning obsolete or considered discarded.
Code here supports MQTT 3.1.1 and it did not change...
However, since MQTT 5 hit the streets this year, we might start to see some traffic.

**Comment by sigusr1** [comment]
But it dosn't support Qos 2 publish.
And I think there is lots of work to be done to fully comform to MQTT 3.1.1 .

**Comment by scaprile** [comment]
If any or some of the sub-projects described in the README,md file do not satisfy your needs or wishes, you are welcome to participate in the forums mentioned there.
Even better, please pinpoint those issues in specific pieces of code and/or contribute your own code to fix them.
