### ISSUE TITLE
MQTTDeserialize_publish uses wrong type for payloadlen parameter

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.embedded-c#2]
migrated from Bugzilla [#481975](https://bugs.eclipse.org/bugs/show_bug.cgi?id=481975)
status UNCONFIRMED severity _critical_ in component _MQTT-Embedded-C_ for _1.2_
Reported in version _unspecified_ on platform _PC_
Assigned to: Ian Craggs

On 2015-11-11 20:05:54 -0500, Joe McIlvain wrote:

> `MQTTDeserialize_publish` takes the `payloadlen` parameter as an `int *` (the address of an `int`), but the `MQTTMessage` struct defines `payloadlen` as of type `size_t`.
> 
> On platforms where `size_t` is bigger than `int`, this causes the upper byte(s) of the `size_t` bytes to be uninitialized/undefined. If the upper byte(s) happen to be zero, this works okay - if they happen to be anything else, the `payloadlen` number becomes huge, and will likely cause a segmentation fault when you try to read the message.
> 
> `MQTTDeserialize_publish` should be fixed to use type `size_t` for the `payloadlen` parameter.

**Comment by jemc** [comment]
Thanks for migrating.

I'm the original reporter of this bug, and I'm here if you need to ask me any questions.

**Comment by jemc** [comment]
How can I make forward progress with this issue ticket?

**Comment by icraggs** [comment]
Hello.  Thanks for reporting and commenting and sorry it's taken so long for me to get to look at this issue.  Obviously, the correct solution would be to change the types of all the size related parameters in the MQTTPacket library to size_t.   Because the library is used in a number of places I will have to check that any knock on effects are resolved too.  I'll target this for release 1.1

**Comment by icraggs** [comment]
We could just zero out the payloadlen field in MQTTMessage before calling MQTTDeserialize_publish.  After all, the MQTT payload length cannot exceed 256MB, so size_t is not actually needed.

**Comment by icraggs** [comment]
I've set the payloadlen field to 0 to address this for now.
