### ISSUE TITLE
Does paho MQTTClient-c support 5.0 version?

### ISSUE THREAD

**Issue by iqramali** [eclipse/paho.mqtt.embedded-c#209]
From this [paho.mqtt](MQTTClient) web page, it says MQTTClient-C does not support 5.0 version. I just want to cross-check once again paho is planned to release 5.0 c libraries in future?

**Comment by benpicco** [comment]
I noticed the [develop](https://github.com/eclipse/paho.mqtt.embedded-c/commits/develop) branch has MQTTv5 commits in it, but I don't know how complete it is.
