### ISSUE TITLE
CC3200 port breaks FreeRTOS scheduler

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.embedded-c#26]
migrated from Bugzilla [#448039](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448039)
status NEW severity _major_ in component _MQTT-Embedded-C_ for _1.1_
Reported in version _unspecified_ on platform _Other_
Assigned to: Ian Craggs

On 2014-10-21 05:51:51 -0400, Tiit RÃ¤tsep wrote:

> The CC3200 port of paho client configures the SysTick timer and interrupt and that seems to break the FreeRTOS scheduler. Most example code for the CC3200 runs technically single threaded after the network configuration so this bug doesn't seem to affect most examples but when tasks need to be switched it's evident that the interrupt is misconfigured.

On 2014-10-21 12:00:44 -0400, Al Stockdill-Mander wrote:

> I am speaking to TI atm on an alternative way to run the timer I need without using SysTick

On 2014-10-21 12:08:26 -0400, Tiit RÃ¤tsep wrote:

> The way I solved it for myself was that I removed the part that messed up SysTick and I manually call the millisecond interrupt in my SysTick handler. That may not be the best solution but it works for me.

On 2014-10-21 12:15:13 -0400, Al Stockdill-Mander wrote:

> If that resolves the issue and other examples still work, please feel free to submit your change, we have Gerrit enabled on the repository, you would need to sign the CLA first (https://www.eclipse.org/legal/CLA.php) and this page talks about how to use Gerrit http://wiki.eclipse.org/Gerrit

On 2014-10-21 12:21:11 -0400, Tiit RÃ¤tsep wrote:

> I will work a bit more on this before I do anything as drastic as commit code here. The solution is not very elegant either as it requires one to manually call the function to increment the millisecond counter and for that one needs to enable the SysTick handler from FreeRTOS config and rebuild that. After that it does work.
> 
> I seem to still have problems with my example. With one connection everything works but I want to have two threads. Both will have their own client and connection. At the moment it seems that calling MQTTYield from both breaks everything (something is not thread safe most likely). Calling MQTTYield only from the subscriber thread makes the other thread time out and generally work extremely slow...

On 2014-10-21 12:53:30 -0400, Tiit RÃ¤tsep wrote:

> Ok ... fixed the multithread issue. It seems that sl_Select can only be called from one thread at a time. I had one thread doing a really long MQTTYield wait (1 s) and the other one needed a short time there. The way I got it to work was to add some osi_Sleep after the waiting to give time for the other thread to do it's thing.
> 
> Back to the timer issue ... I'm still not sure if my solution is the best for this issue as this would not be compatible with most of the code already written for this library as it needs the user to manually call a function inside the SysTick handler. If you can suggest a better solution I'd be more than glad to use that instead but I think this thread here could save someone the whole day of head-scratching I just finished...

**Comment by icraggs** [comment]
I'll be looking to add a better FreeRTOS implementation sometime.
