### ISSUE TITLE
Race condition between MQTTSubscribe and Rx of queued publications

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.embedded-c#6]
migrated from Bugzilla [#477971](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477971)
status ASSIGNED severity _normal_ in component _MQTT-Embedded-C_ for _1.2_
Reported in version _unspecified_ on platform _Other_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[0001-preset-message-handler.patch](https://bugs.eclipse.org/bugs//attachment.cgi?id=256718)_ (ID 256718)

On 2015-09-21 11:36:27 -0400, Alex Lennon wrote:

> Hi,
> 
> Thanks for the great work on the embedded-C libraries. I am currently using these on a Kinetis platform with lwIP.
> 
> I think I see a race condition occurring when I bring up the device. 
> 
> The execution path on power up is
> 
> ConnectNetwork() 
> MQTTConnect() clean session is 0
> MQTTSubscribe(topic) qos is 1
> while(running)
>   MQTTYield()
> 
> I can see we have queued messages on the server from the existing subscription (last time device ran) which are being lost
> 
> Debugging I can see
> 
> Connecting to server 'xxx:1883 socket'
> Connecting as client: 'xxx', user: '', password: ''
> Got ACK packet: 2
> Subscribing to xxx
> Got PUBLISH packet: 3
> Got ACK packet: 9
> Subscribed OK
> 
> So I think what is happening is that MQTTSubscribe() is blocking waiting on the subscription ACK when the publication of a queued message comes in.
> 
> MQTTSubscribe() hasn't yet set-up the message handler so the message is lost.
> 
> I have worked around this by pre-setting the message handler before I issue the MQTTSubscribe but thought I would let you know.
> 
> Regards, Alex

On 2015-09-21 11:46:56 -0400, Alex Lennon wrote:

> Created attachment 256718
> Workaround to preset handler before subscription

On 2015-09-24 16:26:37 -0400, Ian Craggs wrote:

> Hi Alex.
> 
> yes, I can see that would be a problem.
> 
> Why don't we just change the subscribe function so that the callback is set before the subscribe packet is sent, and then if the subscribe fails, we can remove the callback?
> 
> Then, no API changes are needed.

On 2015-09-24 18:23:03 -0400, Alex Lennon wrote:

> Hi Ian,
> 
> "Why don't we just change the subscribe function so that the callback is set before the subscribe packet is sent, and then if the subscribe fails, we can remove the callback?"
> 
> It's a long time since I looked at MQisdp. I'm not sure I can remember the details of the original implementation completely, and I certainly don't know what the current implementation is doing to be able to make sensible commentary.
> 
> I see what you're suggesting and I agree up to a point. My patch isn't offered as a solution so much as a talking point. I completely agree on avoiding API changes and your suggestion would be preferable to my workaround.
> 
> That said, I am not clear on when a broker may provide a message after a connection is established. If it were the case that a retained message on the broker could be provided at any point after a connection ack then we'd still have a race against a subscription call and should probably ensure topic subscriptions are in place before the connection is made?
> 
> But I don't know. What do you think?

**Comment by icraggs** [comment]
I've added the ability to set message handlers separately.  Thanks.
