### ISSUE TITLE
Sequence of session present flag in MQTTConnackFlags

### ISSUE THREAD

**Issue by tcluo** [eclipse/paho.mqtt.embedded-c#64]
Hi all,

I have a question about the struct of MQTTConnackFlags.
According to MQTT3.1.1 specification, bit 0 of Connect Acknowledge Flags is the Session Present Flag. Does the implementation follow the specification?

typedef union
{
	unsigned char all;	/**< all connack flags */
#if defined(REVERSED)
	struct
	{
		unsigned int sessionpresent : 1;    /**< session present flag */
		unsigned int : 7;	  	          /**< unused */
	} bits;
#else
	struct
	{
		unsigned int : 7;	     			/**< unused */
		unsigned int sessionpresent : 1;    /**< session present flag */
	} bits;
#endif
} MQTTConnackFlags;	/**< connack flags byte */

Regards,
TC

**Comment by monstrenyatko** [comment]
I have noticed the same problem on my Arduino Pro Mini (ATmega328).
Definition is reversed (not correct).

After simple [fix](https://github.com/monstrenyatko/ArduinoMqtt/commit/4589a1ae15f07814c3feabfbe40c55bca0943029) the `sessionpresent` flag value is returned correctly from `Mosquitto` broker.

**Comment by icraggs** [comment]
Fixed added to develop branch.  Thanks.
