### ISSUE TITLE
keepalive status is not being checked in cycle()

### ISSUE THREAD

**Issue by sshtel** [eclipse/paho.mqtt.embedded-c#78]
In cycle() of MQTTClient.c, there is a function call to check keepalive message.

Although keepalive time is expired, its status is not being checked and still cycle() returns SUCCESS

https://github.com/eclipse/paho.mqtt.embedded-c/blob/master/MQTTClient-C/src/MQTTClient.c#L282

Does it have to be fixed to check keepalive status at every cycle?

**Comment by sshtel** [comment]
please review https://github.com/eclipse/paho.mqtt.embedded-c/pull/79

**Comment by sshtel** [comment]
Another solution could be to check keepalive() first before reading packets.

**Comment by icraggs** [comment]
I've added a fix for this into both MQTTClient and MQTTClient-C.  Thanks.
