### ISSUE TITLE
Multiple samples directories inside MQTTClient-C

### ISSUE THREAD

**Issue by rafaeldelucena** [eclipse/paho.mqtt.embedded-c#83]
Hello again,

I found two samples directories inside the MQTTClient-C, this is kind of confusing, there's a motivation for this organization?

Thank you

**Comment by icraggs** [comment]
I think I was probably in the middle of moving them to match the location in MQTTPacket and MQTTClient, but forgot to delete the old copy.  I will do that, thanks.

**Comment by icraggs** [comment]
Looks like it's been fixed.  The samples directory at the same level as src is the correct one.
