### ISSUE TITLE
Embedded C client does not detect broker disconnection

### ISSUE THREAD

**Issue by igough** [eclipse/paho.mqtt.embedded-c#84]
If the MQTT broker does not have a connection to the embedded C client (network problems, service failure or just stopping the MQTT server), the client never recognises that the broker is not connected. So even with no Pings being received, the is_connected flag never gets set to 1. When the broker come back online, the client does not attempt to reconnect, so the client is effectively isolated until a reboot.

**Comment by icraggs** [comment]
I've added a fix to the develop branch.

**Comment by icraggs** [comment]
I've also added a test, which works in both C++ and C clients.
