### ISSUE TITLE
do not send PUBCOMP when receiving QOS2 messages from server

### ISSUE THREAD

**Issue by eden-wang** [eclipse/paho.mqtt.embedded-c#89]
when a server sends a qos2 message to a client, the client sends a PUBREC packet to the server. After receiving PUBREC packet, server sends a PUBREL packet to the client. But unfortunately, the client do not send a PUBCOMP packet to the server.

**Comment by icraggs** [comment]
This is fixed in recent updates.

**Comment by eden-wang** [comment]
OK, Thanks
