### ISSUE TITLE
Problem with QOS2 when QOS1 and QOS2 are both defined

### ISSUE THREAD

**Issue by RomNexus6** [eclipse/paho.mqtt.embedded-c#90]
I've found the error inside the sources here:
https://github.com/eclipse/paho.mqtt.embedded-c/pull/86/commits/a4f95674dee0abd3329f9249f95682023c072c4c

it looks that with my gcc 4.3.3 it issues a problem.
I modified in order to always work, with any compiler.

Unfortunately I cannot pull request as my username doesn't match my email when working at office. So the pull was rejected.
Please have a look at my modifications (very simple), and let me know what you think.
Thanks.

**Comment by icraggs** [comment]
Thanks.  Fixed in develop branch, will be in 1.1.
